export interface EmailTemplateOptions {
  title: string;
  message: string;
  actionUrl?: string;
  actionLabel?: string;
  footerText?: string;
}

export const getBaseEmailTemplate = (options: EmailTemplateOptions) => {
  const { title, message, actionUrl, actionLabel, footerText } = options;

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');
    
    body {
      margin: 0;
      padding: 0;
      background-color: #020617;
      font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #f8fafc;
    }
    
    .container {
      max-width: 600px;
      margin: 40px auto;
      background: linear-gradient(145deg, #0f172a 0%, #020617 100%);
      border-radius: 24px;
      overflow: hidden;
      border: 1px solid rgba(255, 255, 255, 0.08);
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
    }
    
    .header {
      padding: 40px 40px 20px;
      text-align: left;
    }
    
    .logo {
      font-size: 24px;
      font-weight: 800;
      letter-spacing: -0.02em;
      background: linear-gradient(to right, #60a5fa, #3b82f6);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 8px;
    }
    
    .brand-sub {
      font-size: 10px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.3em;
      color: #64748b;
    }
    
    .content {
      padding: 20px 40px 40px;
    }
    
    .badge {
      display: inline-block;
      padding: 6px 12px;
      background: rgba(59, 130, 246, 0.1);
      border: 1px solid rgba(59, 130, 246, 0.2);
      border-radius: 100px;
      font-size: 10px;
      font-weight: 700;
      color: #60a5fa;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      margin-bottom: 24px;
    }
    
    h1 {
      font-size: 28px;
      font-weight: 800;
      line-height: 1.2;
      margin: 0 0 20px;
      color: #ffffff;
      letter-spacing: -0.03em;
    }
    
    p {
      font-size: 15px;
      line-height: 1.6;
      color: #94a3b8;
      margin: 0 0 24px;
    }
    
    .button-container {
      margin-top: 32px;
    }
    
    .button {
      display: inline-block;
      padding: 16px 32px;
      background: #3b82f6;
      background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
      color: #ffffff !important;
      text-decoration: none;
      border-radius: 12px;
      font-size: 15px;
      font-weight: 700;
      text-align: center;
      transition: transform 0.2s;
      box-shadow: 0 10px 20px -5px rgba(37, 99, 235, 0.4);
    }
    
    .divider {
      height: 1px;
      background: linear-gradient(to right, transparent, rgba(255, 255, 255, 0.1), transparent);
      margin: 32px 0;
    }
    
    .footer {
      padding: 0 40px 40px;
      text-align: center;
    }
    
    .footer-text {
      font-size: 12px;
      color: #475569;
      line-height: 1.5;
    }
    
    .social {
      margin-top: 20px;
    }
    
    .social a {
      color: #64748b;
      text-decoration: none;
      margin: 0 10px;
      font-size: 12px;
      font-weight: 600;
    }

    .info-card {
      background: rgba(255, 255, 255, 0.03);
      border-radius: 16px;
      padding: 20px;
      border: 1px solid rgba(255, 255, 255, 0.05);
    }

    .info-card-title {
      font-size: 11px;
      font-weight: 800;
      color: #cbd5e1;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      margin-bottom: 8px;
    }

    .info-card-content {
      font-size: 13px;
      color: #64748b;
      margin: 0;
    }

    @media only screen and (max-width: 480px) {
      .container {
        margin: 20px 10px;
      }
      .content {
        padding: 20px;
      }
      h1 {
        font-size: 24px;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo">NEXA OS</div>
      <div class="brand-sub">Advanced Commerce Engine</div>
    </div>
    
    <div class="content">
      <div class="badge">Security Verified</div>
      <h1>${title}</h1>
      <p>${message.replace(/\n/g, "<br>")}</p>
      
      ${actionUrl && actionLabel ? `
      <div class="button-container">
        <a href="${actionUrl}" class="button">${actionLabel}</a>
      </div>
      ` : ''}
      
      <div class="divider"></div>
      
      <div class="info-card">
        <div class="info-card-title">System Intelligence</div>
        <p class="info-card-content">
          This message was generated by the Nexa OS Automated Intelligence system. 
          Your session and data are protected by industry-standard encryption protocols.
        </p>
      </div>
    </div>
    
    <div class="footer">
      <p class="footer-text">${footerText || "Global Enterprise Operating System"}</p>
      <div class="social">
        <a href="#">Support</a>
        <a href="#">Privacy</a>
        <a href="#">Security</a>
      </div>
      <p class="footer-text" style="margin-top: 20px;">
        &copy; ${new Date().getFullYear()} Nexa OS. Developed by Icedmist.
      </p>
    </div>
  </div>
</body>
</html>
  `;
};
